---
title: IRMA
author: Privacy by Design Foundation
email: ''
description: Met IRMA heb je in de hand wat er met jouw gegevens gebeurt.
baseurl: ""
url: ''
languages: ["nl", "fr", "en", "de"]
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-menus
- jekyll-multiple-languages-plugin
